/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6 */

#include "pid_configuration_message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(PIDConfigurationMessage, PIDConfigurationMessage, AUTO)



