# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dron_app_pb2 as dron__app__pb2


class DronStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SettingPID = channel.unary_unary(
                '/dron_app.Dron/SettingPID',
                request_serializer=dron__app__pb2.PIDConfigurationMessage.SerializeToString,
                response_deserializer=dron__app__pb2.RaspberryResponse.FromString,
                )
        self.TestFunction = channel.unary_unary(
                '/dron_app.Dron/TestFunction',
                request_serializer=dron__app__pb2.TestRequest.SerializeToString,
                response_deserializer=dron__app__pb2.TestResponse.FromString,
                )


class DronServicer(object):
    """The greeting service definition.
    """

    def SettingPID(self, request, context):
        """Unary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestFunction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DronServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SettingPID': grpc.unary_unary_rpc_method_handler(
                    servicer.SettingPID,
                    request_deserializer=dron__app__pb2.PIDConfigurationMessage.FromString,
                    response_serializer=dron__app__pb2.RaspberryResponse.SerializeToString,
            ),
            'TestFunction': grpc.unary_unary_rpc_method_handler(
                    servicer.TestFunction,
                    request_deserializer=dron__app__pb2.TestRequest.FromString,
                    response_serializer=dron__app__pb2.TestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dron_app.Dron', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Dron(object):
    """The greeting service definition.
    """

    @staticmethod
    def SettingPID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dron_app.Dron/SettingPID',
            dron__app__pb2.PIDConfigurationMessage.SerializeToString,
            dron__app__pb2.RaspberryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TestFunction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dron_app.Dron/TestFunction',
            dron__app__pb2.TestRequest.SerializeToString,
            dron__app__pb2.TestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
