# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dron_app.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64ron_app.proto\x12\x08\x64ron_app\"\xb2\x01\n\x17PIDConfigurationMessage\x12\x0e\n\x06yaw_kp\x18\x01 \x01(\x05\x12\x0e\n\x06yaw_ki\x18\x02 \x01(\x05\x12\x0e\n\x06yaw_kd\x18\x03 \x01(\x05\x12\x10\n\x08pitch_kp\x18\x04 \x01(\x05\x12\x10\n\x08pitch_ki\x18\x05 \x01(\x05\x12\x10\n\x08pitch_kd\x18\x06 \x01(\x05\x12\x0f\n\x07roll_kp\x18\x07 \x01(\x05\x12\x0f\n\x07roll_ki\x18\x08 \x01(\x05\x12\x0f\n\x07roll_kd\x18\t \x01(\x05\"2\n\x11RaspberryResponse\x12\x1d\n\x15successfullyCompleted\x18\x01 \x01(\x08\x32T\n\x04\x44ron\x12L\n\nSettingPID\x12!.dron_app.PIDConfigurationMessage\x1a\x1b.dron_app.RaspberryResponseb\x06proto3')



_PIDCONFIGURATIONMESSAGE = DESCRIPTOR.message_types_by_name['PIDConfigurationMessage']
_RASPBERRYRESPONSE = DESCRIPTOR.message_types_by_name['RaspberryResponse']
PIDConfigurationMessage = _reflection.GeneratedProtocolMessageType('PIDConfigurationMessage', (_message.Message,), {
  'DESCRIPTOR' : _PIDCONFIGURATIONMESSAGE,
  '__module__' : 'dron_app_pb2'
  # @@protoc_insertion_point(class_scope:dron_app.PIDConfigurationMessage)
  })
_sym_db.RegisterMessage(PIDConfigurationMessage)

RaspberryResponse = _reflection.GeneratedProtocolMessageType('RaspberryResponse', (_message.Message,), {
  'DESCRIPTOR' : _RASPBERRYRESPONSE,
  '__module__' : 'dron_app_pb2'
  # @@protoc_insertion_point(class_scope:dron_app.RaspberryResponse)
  })
_sym_db.RegisterMessage(RaspberryResponse)

_DRON = DESCRIPTOR.services_by_name['Dron']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PIDCONFIGURATIONMESSAGE._serialized_start=29
  _PIDCONFIGURATIONMESSAGE._serialized_end=207
  _RASPBERRYRESPONSE._serialized_start=209
  _RASPBERRYRESPONSE._serialized_end=259
  _DRON._serialized_start=261
  _DRON._serialized_end=345
# @@protoc_insertion_point(module_scope)
